### ISSUE TITLE
Load and safe filters using more secure means

### ISSUE THREAD

**Issue by skovsboll** [mceachen/bloomer#1]
[Marshal.load](https://docs.ruby-lang.org/en/2.0.0/security_rdoc.html#label-Marshal.load) is not secure.

It would be great to be able to load and save the inner BitArray + required params (@k and @capacity ?) directly to a binary file or stream.

**Comment by mceachen** [comment]
PRs are welcome!

**Comment by skovsboll** [comment]
I will make one. By opening an issue first, I just wanted you to verify the idea ;)

**Comment by mceachen** [comment]
Sure. When I wrote this ages ago, my only use case was for internal consumption. I think a safer serialization (like for your bloomed project) certainly makes this idea warranted.

**Comment by skovsboll** [comment]
At first I thought: "There's a straight forward solution". My idea was this:

>anything that can be represented as a hash can be serialized into json, yaml etc. Let's represent `Bloomer` and `Scalable` as a hash.

I tried it. It's not a PR yet, but a WIP branch:
https://github.com/skovsboll/bloomer/blob/feature/serialization/test/bloomer_test.rb#L46

At first it appeared an ok direction. Problems soon started to manifest themselves:

1) in order to represent binary (string) data in either yaml or json I would have to represent it in an encoding that can be handled by those libs. Binary strings broke them. That means twice the memory consumption during encoding and decoding.
2) the size of the resulting structure is roughly twice the size that ´Marshal.dump` produces. That might be a valid trade off for security though.

A pure binary format seems a better idea for those reasons. What's your opinion?

**Comment by mceachen** [comment]
> What's your opinion?

I'd be really surprised if there wasn't a reasonable serialization library that's both efficient to encode, store, and parse, but I don't have one that I've used, as I haven't coded in ruby for half a decade at this point, and haven't stayed up to date with new ruby libraries. I'd suspect a binary encoding (rather than JSON or YAML) might be more efficient at storing all these large numbers.

**Comment by mceachen** [comment]
Thanks for the PR!

**Comment by skovsboll** [comment]
NP :)

Incidently, just read this article https://godaddy.github.io/2018/09/11/redis-ruby-bloom-filter/ which, besides being interesting in itself, also mentions a [PR](https://github.com/peterc/bitarray/pull/9) that got merged into the bitarray gem. The order of the bits in the internal string has changed. That might affect scenarios where one serializes with bitarray v.1.1 but deserializes with 1.2.

I thought about restricting the gemspec to use just one version of bitarray, but maybe it's better to just add a note to the README... 
I'll have to do something in the skovsboll/bloomed repo to load the provided msgpack files the correct way.

**Comment by dalibor** [comment]
@skovsboll Thanks for reading the blog post. :) The change in bitarray is backward compatible, i.e. the order will change only if you set the `reverse_byte: false` because it was and it still is reversing the bits in each byte by default (that is not how Redis stores bits with getbit/setbit operation which is the motivation for providing that option to bitarray).

**Comment by skovsboll** [comment]
@dalibor thank you for clarifying :)
